services:
  postgres:
    image: postgres:16
    container_name: talent-forge-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tf-net

  app:
    image: talent-forge-app
    container_name: talent-forge-app
    restart: unless-stopped
    build:
      context: ./talent_forge
      dockerfile: Dockerfile
    volumes:
      - ./uploads:${APP_UPLOAD_DIR}
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      JAVA_OPTS: ${JAVA_OPTS}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL}
      SERVER_PORT: ${SERVER_PORT}
      APP_UPLOAD_DIR: ${APP_UPLOAD_DIR}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      AI_MATCHER_URL: ${AI_MATCHER_URL}
    ports:
      - "8080:8080"
      - "5005:5005" # <-- Expose debug port
    networks:
      - tf-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "$APP_HEALTHCHECK_URL" ]
      interval: 15s
      timeout: 5s
      retries: 5

  ai-matcher:
    image: talent-forge-ai-matcher
    container_name: talent-forge-ai-matcher
    restart: always
    build:
      context: ./talent_forge_ai_matcher
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      app:
        condition: service_healthy
    environment:
      SPRING_API_URL: ${SPRING_API_URL}
    ports:
      - "8000:8000"
    networks:
      - tf-net


volumes:
  postgres_data:

networks:
  tf-net:
    driver: bridge
