global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-app'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['app:8080'] # Ajuste a porta do seu app Spring Boot
  - job_name: 'ai-matcher'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8000'] # Ajuste a porta do seu app Spring Boot

  # Você pode adicionar mais jobs para monitorar outros serviços aqui
